### ISSUE TITLE
Release for avrdude-6.3

### ISSUE THREAD

**Issue by vanbwodonk** [zkemble/AVRDUDESS#10]
Please release AVRDUDESS for avrdude-6.3. Ubuntu use avrdude-6.3, AVRDUDESS can't detect chip anymore. Already compiled latest code in linux, and AVRDUDESS can detect it. But maybe your official release be better.

**Comment by zkemble** [comment]
Hey Arif, I've actaully just started working on v2.5 so it shouldn't be too long before that's released, possibly September sometime :)

**Comment by vanbwodonk** [comment]
OK, i'll wait for it.

**Comment by DirtyEngineer** [comment]
Really looking forward to 2.5! Thanks Zak for all your hard work.

**Comment by zkemble** [comment]
AVRDUDESS 2.5 and 2.6 have now been released with avrdude 6.3 support!
