### ISSUE TITLE
Feature Request: Read Board Voltage

### ISSUE THREAD

**Issue by jacky4566** [zkemble/AVRDUDESS#21]
It would be nice if there was a button to read board voltage like in Atmel Studio.

**Comment by DirtyEngineer** [comment]
Not really possible as neither Avrdude or most programming hardware has the ability to do this.

**Comment by jacky4566** [comment]
It should be possible though. Atmel Studio can do it with my ICE so the hardware is there. Just a software thing.

I thought you could do it with `-t parms` but it only returns the signature.
So really this needs to be implemented in AVRDUDE first. Just figured `-t parms` would work on ICE...

**Comment by zkemble** [comment]
Yea, reading the board voltage would be an avrdude thing, and if that doesn't support it then avrdudess won't either since we only parse the output of avrdude. I think the -t option is for entering terminal mode, where you can manually edit individual bytes in flash and things.
