### ISSUE TITLE
bit clock (-B)

### ISSUE THREAD

**Issue by MattBelle95** [zkemble/AVRDUDESS#29]
i was trying to upload a hex file to test my atmega32, but i forgot to set the fuse bits for clock source selection, the code uploaded just fine but the delay function was much slower (i was using 12MHz crystal and the default settings was the internal 1MHz), i edited the fuse bits and uploaded the code, nothing bad so far, but when i tried to upload it again it gave me an error rc=-1 and that it can't set clock bit to specified value which was 1.5MHz.
is there a value i should use for clock bits (-B) corresponding to the selected frequency ?

**Comment by zkemble** [comment]
Hey Matt, you've probably got this fixed now, but did you also set the divide clock by 8 fusebit?

**Comment by MattBelle95** [comment]
@zkemble Hey Zak, I didn't get this problem fixed yet, I am using atmega32 it doesn't have divide by 8 fuse bit
![image](https://user-images.githubusercontent.com/20547175/71542648-8b19f980-2971-11ea-9640-69f1c993c521.png)

**Comment by zkemble** [comment]
Have you updated the USBasp firmware (I'm guessing thats the programmer you're using)? They usually come with old firmware where the bit block can only be changed by a jumper on the programmer.

Also send the console output of the error and the new fues values that you tried.

**Comment by MattBelle95** [comment]
I can't get the console output of the error because i bought a new controller.
i used this calculator to get fuse bits values [http://www.engbedded.com/fusecalc](url)
Lfuse:0xFF  Hfuse:0x89

**Comment by MattBelle95** [comment]
I found my old broken controller
here are the screen shots of the error
![image](https://user-images.githubusercontent.com/20547175/71604107-c6cae400-2b68-11ea-8ab2-8c27daab4a9c.png)

and this when i checked -F
![image](https://user-images.githubusercontent.com/20547175/71604121-d8ac8700-2b68-11ea-9728-76a738fa5e7c.png)

**Comment by zkemble** [comment]
It says in the error message "please check for usbasp firmware update", so looks like the programmer firmware needs updating.

**Comment by MattBelle95** [comment]
so the problem is in the usbasp programmer?
where can i get the trusted latest firmware update?

**Comment by DirtyEngineer** [comment]
@MattBelle95 https://www.fischl.de/usbasp/

**Comment by MattBelle95** [comment]
@zkemble i will download the driver and let you kniw what happened, thanks a lot for your effort

**Comment by MattBelle95** [comment]
@zkemble i downloaded the latest version (i already had it installed, but i removed it and installed it again).
it still gives me the same error.
another thing i noticed is when i upload a hex file to my new atmega32 (it uploads successfully and the code behaves as expected) it gives me a warning that it can't set SCK frequency

![image](https://user-images.githubusercontent.com/20547175/72204705-939b2580-3483-11ea-9349-a9a5d9d5e959.png)

**Comment by zkemble** [comment]
I think you only did something with the driver (libUSB), not the firmware. You need a second programmer, like another USBasp or an Arduino with the ArduinoISP sketch loaded onto it to re-program your USBasp. Do a google search for "usbasp firmware update", there are loads of tutorials on how to do it.

There is also usually a jumper on the USBasp somewhere to select fast (1.5MHz) or slow (375KHz) clock (only for the old firmware, new firmware allows setting the clock by software, which is what the error is all about), try shorting or opening it to see if it can then talk to the bad ATmega32.
