### ISSUE TITLE
How to use Avrdudess with esplink?

### ISSUE THREAD

**Issue by Kashyapkoshti** [zkemble/AVRDUDESS#30]
Can you please provide documentation to use avrdudess gui with esplink.

**Comment by zkemble** [comment]
I've never used an esp-link, best thing to do is google "avrdude esp-link". After a quick look it seems the main thing you need to do is enter "net:192.168.0.25:23" (or whatever your esp-link IP is) into the Port box.

**Comment by Kashyapkoshti** [comment]
Which programmer should i select?

**Comment by zkemble** [comment]
Closing because this is not an AVRDUDESS issue and also because I have no idea about esplink!
