### ISSUE TITLE
Arduino Uno ISP

### ISSUE THREAD

**Issue by Samuel-ZDM** [zkemble/AVRDUDESS#36]
Hello!

I am using Arduino Uno as an ISP to record to an Atmega328.
I recorded the ISP code on Arduino Uno.
My programmer is the Atmel AVR ISP and is giving a signature error when I try to detect the board.

Am I using the correct programmer method?

Thank you very much in advance

![atm](https://user-images.githubusercontent.com/26744649/97613979-1e8be300-19f8-11eb-8256-a9481d5d8ec1.png)

**Comment by zkemble** [comment]
Choose "Arduino" as the programmer. There's also a preset (right side) called Arduino as ISP.

**Comment by Samuel-ZDM** [comment]
I did that, but the same mistake happened.
Then, I removed the baud rate and instead of recording on Atmega328, he recorded on Arduino Uno.

**Comment by Samuel-ZDM** [comment]
I was trying here and put the programmer as Atmel AVR ISP and Presets with Arduino as ISP. It looks like it worked.
