### ISSUE TITLE
 Add feature can add "sudo" command

### ISSUE THREAD

**Issue by ahmad-wahyudin** [zkemble/AVRDUDESS#39]
On Linux with usbasp clone chinese, cann't open usb devices: Permissions Denied
![image](https://user-images.githubusercontent.com/16752073/99841642-16f7ce00-2ba1-11eb-8a5f-5fade50b99d3.png)

Using sudo command in terminal
![image](https://user-images.githubusercontent.com/16752073/99841771-473f6c80-2ba1-11eb-9719-75fa738dfa0a.png)

**Comment by zkemble** [comment]
A program running as a non-root user cannot run another program as root with sudo. AVRDUDESS must run as root using `sudo mono avrdudess.exe` or add a udev rule to allow non-root users to access the USBasp. https://github.com/stefanbeller/USBasp/blob/master/bin/linux-nonroot/99-USBasp.rules
