### ISSUE TITLE
Instructions on updating bits.xml to add support for ATTINY1626?

### ISSUE THREAD

**Issue by Eddiiie** [zkemble/AVRDUDESS#53]
Hi,
I am using ATTINY 1626 and am unable to set fuses because they have not been defined.   I added the signature to the XML file but that hard part still remains.   Is there a document anywhere that explains how to update "bits.xml" file to add support for other chips?
```

	<mcu signature="1e9429" name="attiny1626">
		<high>BODLEVEL0,BODLEVEL1,BODLEVEL2,EESAVE,WDTON,,DWEN,RSTDISBL</high>
		<low>CKSEL0,CKSEL1,,,SUT0,SUT1,CKOUT,CKDIV8</low>
		<ext>SELFPRGEN,,,,,,,</ext>
		<lock>LB1,LB2,,,,,,</lock>
	</mcu>

```

**Comment by zkemble** [comment]
Hey Eddiiie, it's not yet possible to add fuse definitions for the t1624 as AVRDUDESS currently only supports high, low, extended and lock fuses, but the t1626 is a newer AVR part which has a different set of fuses (WDTCFG, BODCFG, etc).

**Comment by Eddiiie** [comment]
Thank you.
