### ISSUE TITLE
avr-size.exe is not able to get filepath when there are spaces between filepath

### ISSUE THREAD

**Issue by pardeepk21** [zkemble/AVRDUDESS#9]
avr-size.exe is unable to get filepath when there are spaces between hexfile path for example: 
C:\Users\Hello World\Desktop\New File.hex

Although programmer work fine, but due to this memory bar above flash textbox is not visible.
 I've fixed the issue just replace these lines in the code.
File: avr-size.cs

public int getSize(string file)
        {
            int totalSize = INVALID;
           //CHANGE 1
            file = @"" + file;
            if (File.Exists(file))
            {
                //CHANGE 2
                file = "\"" + file + "\"";
                if (launch(file, null, null, OutputTo.Log))
                {
                    waitForExit();
                    totalSize = parse();
                }
            }
            return totalSize;
        }

**Comment by zkemble** [comment]
Thanks for spotting this! Only change #2 was needed for the fix though.
